:toc:
:toclevels: 4

= Wayk Agent PowerShell Cmdlet
WaykAgent-ps is a PowerShell cmdlet for https://wayk.devolutions.net[Devolutions Wayk Agent]. For assistance or feature requests, please use the https://forum.devolutions.net[Wayk forums] or open a ticket on this github project.

== Installation

On Windows, the regular Windows PowerShell 5.1 already present on the system can be used. On macOS and Linux, you will need 
https://github.com/PowerShell/PowerShell#get-powershell[PowerShell 7]

To launch a PowerShell 7 terminal, use the `pwsh` command.

=== Installation from PSGallery

The Wayk Den PowerShell module is https://www.powershellgallery.com/packages/WaykAgent[available on PSGallery].

[source,sh]
----
Install-Module -Name WaykAgent
Import-Module WaykAgent
----

If you encounter issues with the `Install-Module` command, you may have to https://docs.microsoft.com/en-ca/powershell/gallery/installing-psget[install or update PowerShellGet].

You can then list all commands exported from the `WaykAgent` module:

[source,sh]
----
Get-Command -Module WaykAgent
----

=== Installation from Source

From PowerShell, clone the https://github.com/Devolutions/WaykAgent-ps[WaykAgent-ps] git repository, then import the module from the "WaykAgent" directory.

[source,sh]
----
git clone https://github.com/Devolutions/WaykAgent-ps
Import-Module "./WaykAgent-ps/WaykAgent" -Force
----

== Usage

=== Install/Uninstall

The `Install-WaykAgent` and `Uninstall-WaykAgent` commands can be used to install, update and uninstall Wayk Agent on all platforms. On Windows, the PowerShell console must have elevated rights to perform the installation. On macOS and Linux, sudo will be called to elevate permissions when necessary.

Here is a sample installation, update check and uninstall for macOS:

[source,sh]
----
PS ~/WaykAgent-ps> Install-WaykAgent
Installing Wayk Agent 3.3.2
Downloading https://cdn.devolutions.net/download/Mac/Wayk/3.3.2.0/Wayk.Mac.3.3.2.0.dmg
Password:
PS ~/WaykAgent-ps> Install-WaykAgent
Wayk Agent is already up to date
PS ~/WaykAgent-ps> Uninstall-WaykAgent
----

By default, the `Install-WaykAgent` skips the installation if the local Wayk Agent version is the same as the latest one available, unless the `-Force` parameter is used.

The `-Version` optional parameter can be used to force using a specific version of Wayk Agent instead of the latest one.

The `-NoDesktopShortcut` optional parameter can be used to NOT create a Desktop Shortcut for Wayk Agent

The `-NoStartMenuShortcut` optional parameter can be used to NOT create a Start Menu Shortcut for Wayk Agent

=== wayk-now Command

The Wayk Agent executable path (referred to as 'wayk-now' in CLI commands) can be detected by the `Get-WaykAgentCommand`:

----
Get-WaykAgentCommand
C:\Program Files (x86)\Devolutions\Wayk Agent\WaykAgent.exe
----

This detection correctly handles non-standard installation paths.

=== Version/Package

The `Get-WaykAgentVersion` command detects the current Wayk Agent installation version number.

[source,sh]
----
PS ~/WaykAgent-ps> Get-WaykAgentVersion
3.3.2
----

The `Get-WaykAgentPackage` command discovers the latest Wayk Agent version available and the corresponding download URL.

An optional parameter `-Version` is available if you want to see an older version of Wayk Agent. The `-Platform` parameter can be used to force a specific platform (Windows, macOS, Linux), along with `-Architecture` (x86, x64).

[source,sh]
----
PS ~/WaykAgent-ps> Get-WaykAgentPackage

Url                                                                        Version
---                                                                        -------
https://cdn.devolutions.net/download/Mac/Wayk/3.3.2.0/Wayk.Mac.3.3.2.0.dmg 3.3.2
----

=== Start/Stop/Restart

The `Start-WaykAgent`, `Stop-WaykAgent` and `Restart-WaykAgent` commands can be used to start, stop and restart all Wayk Agent executables and services correctly. This can be particularly useful with the Windows system service.

=== Reboot in Safe Mode

This is an experimental feature for Windows that has been prototyped as part of this PowerShell cmdlet. It will likely be rewritten and integrated directly in the main Wayk Agent software at some point in the future.

Starting from a regular Windows boot environment (not safe mode), open an administrative PowerShell console and use the `Set-WaykAgentSafeMode` command. This will create a copy of the current boot entry, rename it to "Wayk Agent Safe Mode", and set it as the default. A copy of the original boot entry name is saved in the registry to allow reverting to the original state.

You can not reboot the system (`Restart-Computer` or `shutdown /r`), and it will automatically select the "Wayk Agent Safe Mode" boot entry. Once the system is booted, you should be able to connect to it with Wayk Agent.

To revert to the original state, open a PowerShell console again, but use the `Reset-WaykAgentSafeMode` command. This will set the original boot entry as the default, and delete the special "Wayk Agent Safe Mode". You can now restart the computer again and it will boot in its regular state.

=== Wayk Agent Information

The `Get-WaykAgentInfo` command returns information about the different WaykAgent paths

[source,sh]
----
PS ~/WaykAgent-ps> Get-WaykAgentInfo
----

[source,sh]
----
DataPath        : C:/Users/User/AppData/Roaming/Wayk
GlobalDataPath  : C:/ProgramData/Wayk/WaykAgent.cfg
ConfigFile      : C:/Users/User/AppData/Roaming/Wayk/WaykAgent.cfg
LogPath         : C:/Users/User/AppData/Roaming/Wayk/logs
CertificateFile : C:/Users/User/AppData/Roaming/Wayk/WaykAgent.crt
PrivateKeyFile  : C:/Users/User/AppData/Roaming/Wayk/WaykAgent.key
PasswordVault   : C:/Users/User/AppData/Roaming/Wayk/WaykAgent.vault
KnownHostsFile  : C:/Users/User/AppData/Roaming/Wayk/known_hosts
BookmarksFile   : C:/Users/User/AppData/Roaming/Wayk/bookmarks
----

== Configuration
The `Set-WaykAgentConfig` command, is used to modify multiple settings from WaykAgent.

Here is a list of properties that you can modify:

With Windows you can set the global settings or the local settings, by default the local setting is used, if you want to use the global settings in you command add this flag:

[source,sh]
----
PS ~/WaykAgent-ps> Set-WaykAgentConfig -Global
----

=== Get Configuration
The `Get-WaykAgentConfig` command returns the list of configurations from WaykAgent

[source,sh]
----
PS ~/WaykAgent-ps>  Get-WaykAgentConfig
----

[source,sh]
----
FriendlyName               : david
Language                   : en
ControlMode                : AllowRemoteControlServerOnly
AutoLaunchOnUserLogon      : False
ShowMainWindowOnLaunch     : True
MinimizeToNotificationArea : False
ElevationPrompt            : False
AllowPersonalPassword      : True
AllowSystemAuth            : True
AllowNoPassword            : True
PersonalPasswordType       : Generated
PersonalPassword           : 52gk8z
GeneratedPasswordLength    : 6
GeneratedPasswordCharSet   : Alphanumeric
DenEnabled                 : True
DenUrl                     : https://den.wayk.net
QualityMode                : High
LoggingLevel               : Off
LoggingFilter              :
AccessControlViewing       : Disable
AccessControlInteract      : Confirm
AccessControlClipboard     : Disable
AccessControlFileTransfer  : Confirm
AccessControlExec          : Allow
AccessControlChat          : Allow
VersionCheck               : True
----

=== General Properties
==== FriendlyName
The Friendly Name is used for Prompt For Permission (PFP) authentication. It should be easily recognized by your peers.

*Type:* string +
*DefaultValue:* Username of the local user +
*Example:*
[source,sh]
----
PS ~/WaykAgent-ps> Set-WaykAgentConfig -FriendlyName david
----

==== Language
Specifies the language of the application, "en" for English, "fr" for French, "de" German, "zh-CN" for Chinese Simplified, "zh-TW" for Chinese Traditional.

*Type:* string +
*DefaultValue:* Language of the system +
*Accepted values:* "en", "fr", "de", "zh-CN", "zh-TW" +
*Example:*
[source,sh]
----
PS ~/WaykAgent-ps> Set-WaykAgentConfig -Language en
----

==== ControlMode
Specifies the Remote Control Mode of WaykAgent, Both: Both sides are displayed, Client: Only the client side is displayed and Server: Only the server side is displayed.

*Type:* ControlMode +
*DefaultValue:* Both +
*Accepted values:* Both, Client, Server +
*Example:*
[source,sh]
----
PS ~/WaykAgent-ps> Set-WaykAgentConfig -ControlMode Both
----

==== AutoLaunchOnUserLogon
Select this option if you wish to launch Wayk Agent when you log on.

*Type:* boolean +
*DefaultValue:* false +
*Example:*

[source,sh]
----
PS ~/WaykAgent-ps> Set-WaykAgentConfig -AutoLaunchOnUserLogon $false
----

==== ShowMainWindowOnLaunch
this option is to prevent the main application window from showing when Wayk Agent starts. It can be quite useful when the application is automatically launched.

*Type:* boolean +
*DefaultValue:* true +
*Example:*

[source,sh]
----
PS ~/WaykAgent-ps> Set-WaykAgentConfig -ShowMainWindowOnLaunch $true
----

==== MinimizeToNotificationArea
This option is to hide Wayk Agent from the taskbar when minimized.

*Type:* boolean +
*DefaultValue:* false +
*Example:*

[source,sh]
----
PS ~/WaykAgent-ps> Set-WaykAgentConfig -MinimizeToNotificationArea $false
----

==== ElevationPrompt
This option is to disable the prompt to elevate program permissions, and run Wayk Agent without elevated program permissions.

*Type:* boolean +
*DefaultValue:* false +
*Example:*

[source,sh]
----
PS ~/WaykAgent-ps> Set-WaykAgentConfig -ElevationPrompt $false
----

=== Security Properties
==== AllowPersonalPassword
Setting to enabled/disabled SRP: When Secure Remote Password is disabled, the password options are disabled as well.

*Type:* boolean +
*DefaultValue:* true +
*Example:*

[source,sh]
----
PS ~/WaykAgent-ps> Set-WaykAgentConfig -AllowPersonalPassword $true
----

==== AllowSystemAuth
Setting to enabled/disabled SRD: Secure Remote Delegation is the method used for system authentication in the case of unattended remote access. On Windows, remote access is restricted to members of the built-in Administrators or Remote Desktop Users groups.

*Type:* boolean +
*DefaultValue:* true +
*Example:*

[source,sh]
----
PS ~/WaykAgent-ps> Set-WaykAgentConfig -AllowSystemAuth $true
----

==== AllowNoPassword
Setting to enabled/disabled PFP: Prompt for Permission authentication requests explicit consent from the remote user without the need for a password.

*Type:* boolean +
*DefaultValue:* true +
*Example:*

[source,sh]
----
PS ~/WaykAgent-ps> Set-WaykAgentConfig -AllowNoPassword $true
----

==== PersonalPasswordType
Setting to select your password type: +

- Generated Password +
Generate a strong, random password with our password generator which can be configured with the -GeneratedPasswordLength and -GeneratedPasswordCharSet section. +
- Custom Password +
Create a custom password of your own choosing.

*Type:* PersonalPasswordType +
*Accepted values:* Generated, Custom +
*DefaultValue:* Generated +
*Example:*

[source,sh]
----
PS ~/WaykAgent-ps> Set-WaykAgentConfig -PersonalPasswordType Generated
----

==== PersonalPassword
Create a custom password of your own choosing.

*Type:* string +
*Example:*
[source,sh]
----
PS ~/WaykAgent-ps> Set-WaykAgentConfig -PersonalPassword password
----

==== GeneratedPasswordLength
The generated password length

*Type:* int +
*Accepted values:* Between 3 and 9 +
*DefaultValue:* 6 +
*Example:*
[source,sh]
----
PS ~/WaykAgent-ps> Set-WaykAgentConfig -GeneratedPasswordLength 6
----

==== GeneratedPasswordCharSet
The parameter used by the password generator:
The alphanumeric character set contains numbers and letters, excluding 0, O, 1, I for a total of 32 characters. This choice was made to avoid any possible confusion when communicating the password to the other user.

*Type:* GeneratedPasswordCharSet +
*Accepted values:* Numeric, Alphanumeric +
*DefaultValue:* Alphanumeric +
*Example:*
[source,sh]
----
PS ~/WaykAgent-ps> Set-WaykAgentConfig -GeneratedPasswordCharSet Alphanumeric
----

=== Connectivity Properties
==== DenEnabled
Connect to Wayk Den to enable simplified peer-to-peer connectivity with a 6-digit ID.

*Type:* boolean +
*DefaultValue:* true +
*Example:*

[source,sh]
----
PS ~/WaykAgent-ps> Set-WaykAgentConfig -DenEnabled $true
----

==== DenUrl
Connect to the Wayk Den server with the URL

*Type:* string +
*DefaultValue:* "https://den.wayk.net" +
*Example:*

[source,sh]
----
PS ~/WaykAgent-ps> Set-WaykAgentConfig -DenUrl https://den.wayk.net
----

=== Advanced Properties
==== QualityMode
The quality mode allow to adjust the quality of the render to optimize performance.

*Type:* QualityMode +
*Accepted values:* Low, Medium, High +
*DefaultValue:* Medium +
*Example:*

[source,sh]
----
PS ~/WaykAgent-ps> Set-WaykAgentConfig -QualityMode Medium
----

==== LoggingLevel
This Logging level option affects the verbosity of the logging messages.

*Type:* LoggingLevel +
*Accepted values:* Trace, Debug, Info, Warn, Error, Fatal, Off +
*DefaultValue:* Off +
*Example:*

[source,sh]
----
PS ~/WaykAgent-ps> Set-WaykAgentConfig -LoggingLevel Off
----

==== LoggingFilter
This Logging filter option filters the types of messages that are logged.
Do not use unless instructed.

*Type:* string +
*Example:*

[source,sh]
----
PS ~/WaykAgent-ps> Set-WaykAgentConfig -LoggingFilter filter
----

==== VersionCheck
Check for updates when Wayk Agent is launched

*Type:* boolean +
*DefaultValue:* true +
*Example:*

[source,sh]
----
PS ~/WaykAgent-ps> Set-WaykAgentConfig -VersionCheck $true
----

=== Access Control Properties
The Access Control section allows you to restrict access to certain resources shared by the server. In other words, access control defines what can be done to your machine when someone else is connected. You can set each feature independently.

- *Allow*: The feature is enabled.

- *Confirm*: The feature is disabled, but can be enabled after user confirmation during the session.

- *Disable*: The feature is disabled. For security reasons or to enforce company policies, you may want to disable specific features.

==== AccessControlViewing
The viewing access control

*Type:* AccessControl +
*Accepted values:* Allow, Confirm, Disable +
*DefaultValue:* Allow +
*Example:*

[source,sh]
----
PS ~/WaykAgent-ps> Set-WaykAgentConfig -AccessControlViewing Allow
----

==== AccessControlInteract
The interaction access control

*Type:* AccessControl +
*Accepted values:* Allow, Confirm, Disable +
*DefaultValue:* Allow +
*Example:*

[source,sh]
----
PS ~/WaykAgent-ps> Set-WaykAgentConfig -AccessControlInteract Allow
----

==== AccessControlClipboard
The clipboard access control

*Type:* AccessControl +
*Accepted values:* Allow, Confirm, Disable +
*DefaultValue:* Allow +
*Example:*

[source,sh]
----
PS ~/WaykAgent-ps> Set-WaykAgentConfig -AccessControlClipboard Allow
----

==== AccessControlFileTransfer
The file transfer access control

*Type:* AccessControl +
*Accepted values:* Allow, Confirm, Disable +
*DefaultValue:* Allow +
*Example:*

[source,sh]
----
PS ~/WaykAgent-ps> Set-WaykAgentConfig -AccessControlFileTransfer Allow
----

==== AccessControlExec
The execution access control

*Type:* AccessControl +
*Accepted values:* Allow, Confirm, Disable +
*DefaultValue:* Allow +
*Example:*

[source,sh]
----
PS ~/WaykAgent-ps> Set-WaykAgentConfig -AccessControlExec Allow
----

==== AccessControlChat
The chat access control

*Type:* AccessControl +
*Accepted values:* Allow, Confirm, Disable +
*DefaultValue:* Allow +
*Example:*

[source,sh]
----
PS ~/WaykAgent-ps> Set-WaykAgentConfig -AccessControlChat Allow
----

== White Labeling
For more information about White Labeling: +
https://helpwayk.devolutions.net/index.html?advanced_whitelabelbranding.htm

=== Branding Management

==== Test Wayk Agent Branding

The `Test-WaykAgentBranding` command with the parameter `BrandingPath` will inform you if the `branding.7z` is in a correct format, if the json file is correct, and if the encoding of the json file is correct.

[source,sh]
----
PS ~/WaykAgent-ps> Test-WaykAgentBranding -BrandingPath https://github.com/Devolutions/WaykAgent-ps/blob/master/samples/branding.7z?raw=true
----

[source,sh]
----
PS ~/WaykAgent-ps> Test-WaykAgentBranding -BrandingPath C:\Devolutions\BrandingFolder\branding.7z
----

==== Set Wayk Agent Branding

The `Set-WaykAgentBranding` command with the parameter `BrandingPath` will copy your archive `branding.zip` to the correct path of WaykAgent. You can find a https://github.com/Devolutions/WaykAgent-ps/blob/master/samples/branding.zip?raw=true[sample branding.zip file here].

[source,sh]
----
PS ~/WaykAgent-ps> Set-WaykAgentBranding -BrandingPath C:\branding.zip
----

==== Reset Wayk Agent Branding

The `Reset-WaykAgentBranding` command remove the `branding.7z` from the `%APPDATA%\Wayk` and the `%PROGRAMDATA%\Wayk` paths.

== Wayk Agent Unique ID

==== Get Wayk Agent Unique ID

The `Get-WaykAgentUniqueID` command returns the unique ID of Wayk Agent

[source,sh]
----
PS ~/WaykAgent-ps> Get-WaykAgentUniqueID
xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
----

== Machine Registration

The `Register-WaykAgent` command can be used to automatically connect and register to a https://github.com/Devolutions/WaykDen-ps/blob/master/docs/deployment-automation.adoc#enrollment[Wayk Den using an enrollment token]. It is the PowerShell equivalent of the "wayk-now enroll" command. The most common usage is with the -TokenId and -DenUrl parameters:

----
Register-WaykAgent -TokenId 'f762156f-9470-4dcc-9ba3-157437e465ce' -DenUrl 'https://den.contoso.com'
----

The `-TokenData` can also be used to pass the full token data (no separate `-DenUrl` parameter is necessary):

----
Register-WaykAgent -TokenData 'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2Rlbi5idXp6d29yZC5tYXJrZXRpbmciLCJqdGkiOiJmNzYyMTU2Zi05NDcwLTRkY2MtOWJhMy0xNTc0MzdlNDY1Y2UiLCJpYXQiOjE1OTcwODI3NjMsImV4cCI6MTU5OTY3NDc2M30.hWaKDCHXuCHd6dXNwkvdCVKSY3eZXN7qWKKPkeSFdT4NkhT8H-p_GNXxpXuE-OTfOFislg9F1eacV5p86ef3qukgWp_qw_LJ6O8kBcq1AQccSFM7nkyB5yvXnAFbvuOJyUnGxmGG0eO9b3ihA3RVZdQFaQrn7uDyQSAnPssq1M0tli9ywcXki__IzAFI7ZXDPZPKwEw_xedADNSNfL7Gb_pnFnTsyuSOLynq7T8TPdR0G5YSG6palnRjWKPlZeEfYhYq6qu_zDSDLDLgfLFxjSxVHUGd62cSC3r1ne5Viu7GZKZIQJR2T1ljWPBfttqYjrHZMTe6JiU3-E7VUVYLVQ'
----

For the sake of convenience, the token can also be saved to a file and passed using the `-TokenPath` parameter:

----
Register-WaykAgent -TokenPath 'C:\token.txt'
----

== Log Management

==== Enable WaykAgent Logs

The command `Enable-WaykAgentLogs` will enable the logs on WaykAgent with the Logging Level `Debug` by default, you can choose this one with the parameter `LoggingLevel` and you can choose to restart WaykAgent with the command `-Restart`, because the changes will only be applied after an application restart.

[source,sh]
----
PS ~/WaykAgent-ps> Enable-WaykAgentLogs -Restart -LoggingLevel Info
----

==== Disable WaykAgent Logs

The command `Disable-WaykAgentLogs` will disable the logs on WaykAgent, you can choose to restart WaykAgent with the command `-Restart`, because the changes will only be applied after an application restart.
[source,sh]
----
PS ~/WaykAgent-ps> Disable-WaykAgentLogs -Restart
----

==== Export WaykAgent Logs

The command `Export-WaykAgentLogs` will export the logs from WaykAgent, you need to set the parameter `-ExportPath` to choose the destination of the logs
[source,sh]
----
PS ~/WaykAgent-ps> Export-WaykAgentLogs -ExportPath C:\Users\user\Desktop
----

==== Clear WaykAgent Logs

The command `Clear-WaykAgentLogs` will clear the logs from WaykAgent
[source,sh]
----
PS ~/WaykAgent-ps> Clear-WaykAgentLogs
----
