:toc:
:toclevels: 4

= Wayk Now PowerShell Cmdlet
WaykNow-ps is a PowerShell cmdlet for https://wayk.devolutions.net[Devolutions Wayk Now]. For assistance or feature requests, please use the https://forum.devolutions.net/#WaykNow[Wayk Now forums] or open a ticket on this github project.

== Installation

On Windows, the regular Windows PowerShell 5.1 already present on the system can be used. On macOS and Linux, you will need 
https://github.com/PowerShell/PowerShell#get-powershell[PowerShell 7]

To launch a PowerShell 7 terminal, use the `pwsh` command.

=== Installation from PSGallery

The Wayk Den PowerShell module is https://www.powershellgallery.com/packages/WaykNow[available on PSGallery].

[source,sh]
----
Install-Module -Name WaykNow
Import-Module WaykNow
----

If you encounter issues with the `Install-Module` command, you may have to https://docs.microsoft.com/en-ca/powershell/gallery/installing-psget[install or update PowerShellGet].

You can then list all commands exported from the `WaykNow` module:

[source,sh]
----
Get-Command -Module WaykNow
----

=== Installation from Source

From PowerShell, clone the https://github.com/Devolutions/WaykNow-ps[WaykNow-ps] git repository, then import the module from the "WaykNow" directory.

[source,sh]
----
git clone https://github.com/Devolutions/WaykNow-ps
Import-Module "./WaykNow-ps/WaykNow" -Force
----

== Usage

=== Install/Uninstall

The `Install-WaykNow` and `Uninstall-WaykNow` commands can be used to install, update and uninstall Wayk Now on all platforms. On Windows, the PowerShell console must have elevated rights to perform the installation. On macOS and Linux, sudo will be called to elevate permissions when necessary.

Here is a sample installation, update check and uninstall for macOS:

[source,sh]
----
PS ~/WaykNow-ps> Install-WaykNow
Installing Wayk Now 3.3.2
Downloading https://cdn.devolutions.net/download/Mac/Wayk/3.3.2.0/Wayk.Mac.3.3.2.0.dmg
Password:
PS ~/WaykNow-ps> Install-WaykNow
Wayk Now is already up to date
PS ~/WaykNow-ps> Uninstall-WaykNow
----

By default, the `Install-WaykNow` skips the installation if the local Wayk Now version is the same as the latest one available, unless the `-Force` parameter is used.

The `-Version` optional parameter can be used to force using a specific version of Wayk Now instead of the latest one.

The `-NoDesktopShortcut` optional parameter can be used to NOT create a Desktop Shortcut for Wayk Now

The `-NoStartMenuShortcut` optional parameter can be used to NOT create a Start Menu Shortcut for Wayk Now

=== Version/Package

The `Get-WaykNowVersion` command detects the current Wayk Now installation version number.

[source,sh]
----
PS ~/WaykNow-ps> Get-WaykNowVersion
3.3.2
----

The `Get-WaykNowPackage` command discovers the latest Wayk Now version available and the corresponding download URL.

An optional parameter `-Version` is available if you want to see an older version of Wayk Now. The `-Platform` parameter can be used to force a specific platform (Windows, macOS, Linux), along with `-Architecture` (x86, x64).

[source,sh]
----
PS ~/WaykNow-ps> Get-WaykNowPackage

Url                                                                        Version
---                                                                        -------
https://cdn.devolutions.net/download/Mac/Wayk/3.3.2.0/Wayk.Mac.3.3.2.0.dmg 3.3.2
----

=== Start/Stop/Restart

The `Start-WaykNow`, `Stop-WaykNow` and `Restart-WaykNow` commands can be used to start, stop and restart all Wayk Now executables and services correctly. This can be particularly useful with the Windows system service.

=== Reboot in Safe Mode

This is an experimental feature for Windows that has been prototyped as part of this PowerShell cmdlet. It will likely be rewritten and integrated directly in the main Wayk Now software at some point in the future.

Starting from a regular Windows boot environment (not safe mode), open an administrative PowerShell console and use the `Set-WaykNowSafeMode` command. This will create a copy of the current boot entry, rename it to "Wayk Now Safe Mode", and set it as the default. A copy of the original boot entry name is saved in the registry to allow reverting to the original state.

You can not reboot the system (`Restart-Computer` or `shutdown /r`), and it will automatically select the "Wayk Now Safe Mode" boot entry. Once the system is booted, you should be able to connect to it with Wayk Now.

To revert to the original state, open a PowerShell console again, but use the `Reset-WaykNowSafeMode` command. This will set the original boot entry as the default, and delete the special "Wayk Now Safe Mode". You can now restart the computer again and it will boot in its regular state.

=== Wayk Now Information

The `Get-WaykNowInfo` command returns information about the different WaykNow paths

[source,sh]
----
PS ~/WaykNow-ps> Get-WaykNowInfo
----

[source,sh]
----
DataPath        : C:/Users/User/AppData/Roaming/Wayk
GlobalDataPath  : C:/ProgramData/Wayk/WaykNow.cfg
ConfigFile      : C:/Users/User/AppData/Roaming/Wayk/WaykNow.cfg
LogPath         : C:/Users/User/AppData/Roaming/Wayk/logs
CertificateFile : C:/Users/User/AppData/Roaming/Wayk/WaykNow.crt
PrivateKeyFile  : C:/Users/User/AppData/Roaming/Wayk/WaykNow.key
PasswordVault   : C:/Users/User/AppData/Roaming/Wayk/WaykNow.vault
KnownHostsFile  : C:/Users/User/AppData/Roaming/Wayk/known_hosts
BookmarksFile   : C:/Users/User/AppData/Roaming/Wayk/bookmarks
----

== Configuration
The `Set-WaykNowConfig` command, is used to modify multiple settings from WaykNow.

Here is a list of properties that you can modify:

With Windows you can set the global settings or the local settings, by default the local setting is used, if you want to use the global settings in you command add this flag:

[source,sh]
----
PS ~/WaykNow-ps> Set-WaykNowConfig -Global
----

=== Get Configuration
The `Get-WaykNowConfig` command returns the list of configurations from WaykNow

[source,sh]
----
PS ~/WaykNow-ps>  Get-WaykNowConfig
----

[source,sh]
----
FriendlyName               : david
Language                   : en
ControlMode                : AllowRemoteControlServerOnly
AutoLaunchOnUserLogon      : False
ShowMainWindowOnLaunch     : True
MinimizeToNotificationArea : False
ElevationPrompt            : False
AllowPersonalPassword      : True
AllowSystemAuth            : True
AllowNoPassword            : True
PersonalPasswordType       : Generated
PersonalPassword           : 52gk8z
GeneratedPasswordLength    : 6
GeneratedPasswordCharSet   : Alphanumeric
DenEnabled                 : True
DenUrl                     : https://den.wayk.net
QualityMode                : High
LoggingLevel               : Off
LoggingFilter              :
AccessControlViewing       : Disable
AccessControlInteract      : Confirm
AccessControlClipboard     : Disable
AccessControlFileTransfer  : Confirm
AccessControlExec          : Allow
AccessControlChat          : Allow
----

=== General Properties
==== FriendlyName
The Friendly Name is used for Prompt For Permission (PFP) authentication. It should be easily recognized by your peers.

*Type:* string +
*DefaultValue:* Username of the local user +
*Example:*
[source,sh]
----
PS ~/WaykNow-ps> Set-WaykNowConfig -FriendlyName david
----

==== Language
Specifies the language of the application, "en" for English, "fr" for French, "de" German, "zh-CN" for Chinese Simplified, "zh-TW" for Chinese Traditional.

*Type:* string +
*DefaultValue:* Language of the system +
*Accepted values:* "en", "fr", "de", "zh-CN", "zh-TW" +
*Example:*
[source,sh]
----
PS ~/WaykNow-ps> Set-WaykNowConfig -Language en
----

==== ControlMode
Specifies the Remote Control Mode of WaykNow, Both: Both sides are displayed, Client: Only the client side is displayed and Server: Only the server side is displayed.

*Type:* ControlMode +
*DefaultValue:* Both +
*Accepted values:* Both, Client, Server +
*Example:*
[source,sh]
----
PS ~/WaykNow-ps> Set-WaykNowConfig -ControlMode Both
----

==== AutoLaunchOnUserLogon
Select this option if you wish to launch Wayk Now when you log on.

*Type:* boolean +
*DefaultValue:* false +
*Example:*

[source,sh]
----
PS ~/WaykNow-ps> Set-WaykNowConfig -AutoLaunchOnUserLogon false
----

==== ShowMainWindowOnLaunch
this option is to prevent the main application window from showing when Wayk Now starts. It can be quite useful when the application is automatically launched.

*Type:* boolean +
*DefaultValue:* true +
*Example:*

[source,sh]
----
PS ~/WaykNow-ps> Set-WaykNowConfig -ShowMainWindowOnLaunch true
----

==== MinimizeToNotificationArea
This option is to hide Wayk Now from the taskbar when minimized.

*Type:* boolean +
*DefaultValue:* false +
*Example:*

[source,sh]
----
PS ~/WaykNow-ps> Set-WaykNowConfig -MinimizeToNotificationArea false
----

==== ElevationPrompt
This option is to disable the prompt to elevate program permissions, and run Wayk Now without elevated program permissions.

*Type:* boolean +
*DefaultValue:* false +
*Example:*

[source,sh]
----
PS ~/WaykNow-ps> Set-WaykNowConfig -ElevationPrompt false
----

=== Security Properties
==== AllowPersonalPassword
Setting to enabled/disabled SRP: When Secure Remote Password is disabled, the password options are disabled as well.

*Type:* boolean +
*DefaultValue:* true +
*Example:*

[source,sh]
----
PS ~/WaykNow-ps> Set-WaykNowConfig -AllowPersonalPassword true
----

==== AllowSystemAuth
Setting to enabled/disabled SRD: Secure Remote Delegation is the method used for system authentication in the case of unattended remote access. On Windows, remote access is restricted to members of the built-in Administrators or Remote Desktop Users groups.

*Type:* boolean +
*DefaultValue:* true +
*Example:*

[source,sh]
----
PS ~/WaykNow-ps> Set-WaykNowConfig -AllowSystemAuth true
----

==== AllowNoPassword
Setting to enabled/disabled PFP: Prompt for Permission authentication requests explicit consent from the remote user without the need for a password.

*Type:* boolean +
*DefaultValue:* true +
*Example:*

[source,sh]
----
PS ~/WaykNow-ps> Set-WaykNowConfig -AllowNoPassword true
----

==== PersonalPasswordType
Setting to select your password type: +

- Generated Password +
Generate a strong, random password with our password generator which can be configured with the -GeneratedPasswordLength and -GeneratedPasswordCharSet section. +
- Custom Password +
Create a custom password of your own choosing.

*Type:* PersonalPasswordType +
*Accepted values:* Generated, Custom +
*DefaultValue:* Generated +
*Example:*

[source,sh]
----
PS ~/WaykNow-ps> Set-WaykNowConfig -PersonalPasswordType Generated
----

==== PersonalPassword
Create a custom password of your own choosing.

*Type:* string +
*Example:*
[source,sh]
----
PS ~/WaykNow-ps> Set-WaykNowConfig -PersonalPassword password
----

==== GeneratedPasswordLength
The generated password length

*Type:* int +
*Accepted values:* Between 3 and 9 +
*DefaultValue:* 6 +
*Example:*
[source,sh]
----
PS ~/WaykNow-ps> Set-WaykNowConfig -GeneratedPasswordLength 6
----

==== GeneratedPasswordCharSet
The parameter used by the password generator:
The alphanumeric character set contains numbers and letters, excluding 0, O, 1, I for a total of 32 characters. This choice was made to avoid any possible confusion when communicating the password to the other user.

*Type:* GeneratedPasswordCharSet +
*Accepted values:* Numeric, Alphanumeric +
*DefaultValue:* Alphanumeric +
*Example:*
[source,sh]
----
PS ~/WaykNow-ps> Set-WaykNowConfig -GeneratedPasswordCharSet Alphanumeric
----

=== Connectivity Properties
==== DenEnabled
Connect to Wayk Den to enable simplified peer-to-peer connectivity with a 6-digit ID.

*Type:* boolean +
*DefaultValue:* true +
*Example:*

[source,sh]
----
PS ~/WaykNow-ps> Set-WaykNowConfig -DenEnabled true
----

==== DenUrl
Connect to the Wayk Den server with the URL

*Type:* string +
*DefaultValue:* "https://den.wayk.net" +
*Example:*

[source,sh]
----
PS ~/WaykNow-ps> Set-WaykNowConfig -DenUrl https://den.wayk.net
----

=== Advanced Properties
==== QualityMode
The quality mode allow to adjust the quality of the render to optimize performance.

*Type:* QualityMode +
*Accepted values:* Low, Medium, High +
*DefaultValue:* Medium +
*Example:*

[source,sh]
----
PS ~/WaykNow-ps> Set-WaykNowConfig -QualityMode Medium
----

==== LoggingLevel
This Logging level option affects the verbosity of the logging messages.

*Type:* LoggingLevel +
*Accepted values:* Trace, Debug, Info, Warn, Error, Fatal, Off +
*DefaultValue:* Off +
*Example:*

[source,sh]
----
PS ~/WaykNow-ps> Set-WaykNowConfig -LoggingLevel Off
----

==== LoggingFilter
This Logging filter option filters the types of messages that are logged.
Do not use unless instructed.

*Type:* string +
*Example:*

[source,sh]
----
PS ~/WaykNow-ps> Set-WaykNowConfig -LoggingFilter filter
----

=== Access Control Properties
The Access Control section allows you to restrict access to certain resources shared by the server. In other words, access control defines what can be done to your machine when someone else is connected. You can set each feature independently.

- *Allow*: The feature is enabled.

- *Confirm*: The feature is disabled, but can be enabled after user confirmation during the session.

- *Disable*: The feature is disabled. For security reasons or to enforce company policies, you may want to disable specific features.

==== AccessControlViewing
The viewing access control

*Type:* AccessControl +
*Accepted values:* Allow, Confirm, Disable +
*DefaultValue:* Allow +
*Example:*

[source,sh]
----
PS ~/WaykNow-ps> Set-WaykNowConfig -AccessControlViewing Allow
----

==== AccessControlInteract
The interaction access control

*Type:* AccessControl +
*Accepted values:* Allow, Confirm, Disable +
*DefaultValue:* Allow +
*Example:*

[source,sh]
----
PS ~/WaykNow-ps> Set-WaykNowConfig -AccessControlInteract Allow
----

==== AccessControlClipboard
The clipboard access control

*Type:* AccessControl +
*Accepted values:* Allow, Confirm, Disable +
*DefaultValue:* Allow +
*Example:*

[source,sh]
----
PS ~/WaykNow-ps> Set-WaykNowConfig -AccessControlClipboard Allow
----

==== AccessControlFileTransfer
The file transfer access control

*Type:* AccessControl +
*Accepted values:* Allow, Confirm, Disable +
*DefaultValue:* Allow +
*Example:*

[source,sh]
----
PS ~/WaykNow-ps> Set-WaykNowConfig -AccessControlFileTransfer Allow
----

==== AccessControlExec
The execution access control

*Type:* AccessControl +
*Accepted values:* Allow, Confirm, Disable +
*DefaultValue:* Allow +
*Example:*

[source,sh]
----
PS ~/WaykNow-ps> Set-WaykNowConfig -AccessControlExec Allow
----

==== AccessControlChat
The chat access control

*Type:* AccessControl +
*Accepted values:* Allow, Confirm, Disable +
*DefaultValue:* Allow +
*Example:*

[source,sh]
----
PS ~/WaykNow-ps> Set-WaykNowConfig -AccessControlChat Allow
----

== White Labeling
For more information about White Labeling: +
https://helpwayk.devolutions.net/index.html?advanced_whitelabelbranding.htm

=== Branding Management

==== Test Wayk Now Branding

The `Test-WaykNowBranding` command with the parameter `BrandingPath` will inform you if the `branding.7z` is in a correct format, if the json file is correct, and if the encoding of the json file is correct.

[source,sh]
----
PS ~/WaykNow-ps> Test-WaykNowBranding -BrandingPath https://github.com/Devolutions/WaykNow-ps/blob/master/samples/branding.7z?raw=true
----

[source,sh]
----
PS ~/WaykNow-ps> Test-WaykNowBranding -BrandingPath C:\Devolutions\BrandingFolder\branding.7z
----

==== Set Wayk Now Branding

The `Set-WaykNowBranding` command with the parameter `BrandingPath` will copy your archive `branding.zip` to the correct path of WaykNow. You can find a https://github.com/Devolutions/WaykNow-ps/blob/master/samples/branding.zip?raw=true[sample branding.zip file here].

[source,sh]
----
PS ~/WaykNow-ps> Set-WaykNowBranding -BrandingPath C:\branding.zip
----

==== Reset Wayk Now Branding

The `Reset-WaykNowBranding` command remove the `branding.7z` from the `%APPDATA%\Wayk` and the `%PROGRAMDATA%\Wayk` paths.

== Wayk Now License

==== Set Wayk Now License

The `Set-WaykNowLicense` command with the parameter `License`, sets your Wayk Now license.

[source,sh]
----
PS ~/WaykNow-ps> Set-WaykNowLicense -License XXXXX-XXXXX-XXXXX-XXXXX-XXXXX
----

==== Get Wayk Now License

The `Get-WaykNowLicense` command returns your license from Wayk Now.

[source,sh]
----
PS ~/WaykNow-ps> Get-WaykNowLicense 
XXXXX-XXXXX-XXXXX-XXXXX-XXXXX
----

==== Reset Wayk Now license

The `Reset-WaykNowLicense` command removes your license from Wayk Now.

[source,sh]
----
PS ~/WaykNow-ps> Reset-WaykNowLicense 

----

== Wayk Now Unique ID

==== Get Wayk Now Unique ID

The `Get-WaykNowUniqueID` command returns the unique ID of Wayk Now

[source,sh]
----
PS ~/WaykNow-ps> Get-WaykNowUniqueID
xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
----

== Machine Registration

The `Register-WaykNow` command can be used to automatically connect and register to a https://github.com/Devolutions/WaykDen-ps/blob/master/docs/deployment-automation.adoc#enrollment[Wayk Den using an enrollment token]. It is the PowerShell equivalent of the "wayk-now enroll" command. The most common usage is with the -TokenId and -DenUrl parameters:

----
Register-WaykNow -TokenId 'f762156f-9470-4dcc-9ba3-157437e465ce' -DenUrl 'https://den.contoso.com'
----

The `-TokenData` can also be used to pass the full token data (no separate `-DenUrl` parameter is necessary):

----
Register-WaykNow -TokenData 'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2Rlbi5idXp6d29yZC5tYXJrZXRpbmciLCJqdGkiOiJmNzYyMTU2Zi05NDcwLTRkY2MtOWJhMy0xNTc0MzdlNDY1Y2UiLCJpYXQiOjE1OTcwODI3NjMsImV4cCI6MTU5OTY3NDc2M30.hWaKDCHXuCHd6dXNwkvdCVKSY3eZXN7qWKKPkeSFdT4NkhT8H-p_GNXxpXuE-OTfOFislg9F1eacV5p86ef3qukgWp_qw_LJ6O8kBcq1AQccSFM7nkyB5yvXnAFbvuOJyUnGxmGG0eO9b3ihA3RVZdQFaQrn7uDyQSAnPssq1M0tli9ywcXki__IzAFI7ZXDPZPKwEw_xedADNSNfL7Gb_pnFnTsyuSOLynq7T8TPdR0G5YSG6palnRjWKPlZeEfYhYq6qu_zDSDLDLgfLFxjSxVHUGd62cSC3r1ne5Viu7GZKZIQJR2T1ljWPBfttqYjrHZMTe6JiU3-E7VUVYLVQ'
----

For the sake of convenience, the token can also be saved to a file and passed using the `-TokenPath` parameter:

----
Register-WaykNow -TokenPath 'C:\token.txt'
----

== Log Management

==== Enable WaykNow Logs

The command `Enable-WaykNowLogs` will enable the logs on WaykNow with the Logging Level `Debug` by default, you can choose this one with the parameter `LoggingLevel` and you can choose to restart WaykNow with the command `-Restart`, because the changes will only be applied after an application restart.

[source,sh]
----
PS ~/WaykNow-ps> Enable-WaykNowLogs -Restart -LoggingLevel Info
----

==== Disable WaykNow Logs

The command `Disable-WaykNowLogs` will disable the logs on WaykNow, you can choose to restart WaykNow with the command `-Restart`, because the changes will only be applied after an application restart.
[source,sh]
----
PS ~/WaykNow-ps> Disable-WaykNowLogs -Restart
----

==== Export WaykNow Logs

The command `Export-WaykNowLogs` will export the logs from WaykNow, you need to set the parameter `-ExportPath` to choose the destination of the logs
[source,sh]
----
PS ~/WaykNow-ps> Export-WaykNowLogs -ExportPath C:\Users\user\Desktop
----

==== Clear WaykNow Logs

The command `Clear-WaykNowLogs` will clear the logs from WaykNow
[source,sh]
----
PS ~/WaykNow-ps> Clear-WaykNowLogs
----
